apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox-statefulset
spec:
  serviceName: "busybox"
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.32.1
        command: ["sh", "-c", "while true; do sleep 5; done"]
  volumeClaimTemplates:
  - metadata:
      name: busybox-persistent-storage
    spec:
      accessModes: ["WriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Mi