[package]
name = "jetstream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
indextree = "4.6.0"
rand = "0.8.5"
rdkafka = { version = "0.34.0", features = ["cmake-build"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.49"
timely = { version = "0.12.0", features = ["bincode"] }
