apiVersion: v1
kind: ConfigMap
metadata:
  name: jetstream-snapshot-config
data:
  statefulset_name: jetstream
  replica_count: 2
  snapshot_leader_uri: http://jetstream-snapshot-svc.svc.cluster.local:29091
  snapshot_svc_port: 29091
---
apiVersion: v1
kind: Service
metadata:
  name: jetstream-snapshot-svc
spec:
  selector:
    statefulset.kubernetes.io/pod-name: jetstream-0 # always pod 0
  ports:
    - protocol: TCP
      port: 29091
      targetPort: 29091
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jetstream
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: worker
        image: alpine:latest
        ports:
        - containerPort: 29091
          name: jetstream-snapshot
        volumeMounts:
          - name: jetstream-config-volume
            mountPath: /etc/jetstream/snapshot/config.yaml
            subPath: config.yaml
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
          cpu: 1
          memory: 2Gi
