[package]
name = "malstrom-kafka"
version = "0.1.0"
edition = "2021"

[dependencies]
bon = { version = "3.5.1", features = ["experimental-overwritable"] }
malstrom = { path = "../malstrom-core" }
rdkafka = { version = "0.36.2"}
thiserror = "2.0.12"
tracing = "0.1.41"

