apiVersion: v1
kind: Service
metadata:
  name: malstrom-svc
  labels:
    app: malstrom
spec:
  selector:
    app: malstrom
  clusterIP: None
  ports:
  - name: malstrom-p2p
    port: 29091
    targetPort: 29091
  publishNotReadyAddresses: true # important for discovery
----
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: malstrom-app
spec:
  replicas: 3
  serviceName: malstrom-svc
  # this is important, it tells k8s to start all replicas immediatly
  # we need this to ensure our discovery works correctly
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: malstrom
  template:
    metadata:
      labels:
        app: malstrom
    spec:
      containers:
        - name: malstrom-worker
          image: localhost/malstrom-k8s:example
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 29091
          env:
            - name: RUST_LOG
              value: malstrom_k8s
            - name: MALSTROM_K8S_SCALE
              value: "3"
            - name: MALSTROM_K8S_HOSTNAME
              valueFrom:
                fieldRef: {fieldPath: metadata.name}
            - name: MALSTROM_K8S_STS_NS
              valueFrom:
                fieldRef: {fieldPath: metadata.namespace}
            - name: MALSTROM_K8S_SVC_NAME
              value: "malstrom-svc"
