{{- if .Values.artifactManager.deploy -}}
apiVersion: v1
kind: Service
metadata:
  name: artifact-manager
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.artifactManager.service.type }}
  selector:
    app.malstrom.io/name: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.artifactManager.service.port }}
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifact-store
spec:
  {{ if .Values.artifactManager.storageClassName -}}
    storageClassName: {{ default "default" .Values.artifactManager.storageClassName }}
  {{ end -}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "1Gi" .Values.artifactManager.size }}
{{ end }}