apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.malstrom.io/name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app.malstrom.io/name: {{ .Values.name }}
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.malstrom.io/name: {{ .Values.name }}
    spec:
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      affinity: {{ toYaml .Values.affinity }}
      volumes:
        {{ if .Values.artifactManager.deploy -}}
        - name: artifacts
          persistentVolumeClaim:
            claimName: artifact-store
        {{- else -}}
          []
        {{- end }}
      imagePullSecrets: 
        {{ toYaml .Values.imagePullSecrets }}
      containers:
        {{- with .Values.operator }}
        - name: operator
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: {{ .image.imagePullPolicy }}
          resources: {{ toYaml .resources }}
          env:
            - name: RUST_LOG
              value: {{ lower $.Values.logLevel }}
        {{ end }}
        {{- if .Values.artifactManager.deploy -}}
        {{- with .Values.artifactManager -}}
        - name: artifact-manager
          image: '{{ .image.repository }}:{{ .image.tag }}'
          imagePullPolicy: {{ .image.imagePullPolicy }}
          resources: {{ toYaml .resources }}
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: artifacts
              mountPath: /app/artifacts
              subPath: ''
          livenessProbe:
            httpGet:
              host: ''
              path: /health
              port: 8000
          env:
            - name: RUST_LOG
              value: {{ lower $.Values.logLevel }}
        {{- end -}}
        {{- end }}
        