apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}-watcher
rules:
- apiGroups: ["malstrom.io"]
  resources: ["jobs"]
  verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $.Values.serviceAccount.name }}-watcher
  apiGroup: rbac.authorization.k8s.io
---

{{- range $namespace := .Values.serviceAccount.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Values.serviceAccount.name }}-role
  namespace: {{ $namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["malstrom.io"]
  resources: ["*"]
  verbs: ["*"]
- verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  apiGroups: [""]
  resources: ["services"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.serviceAccount.name }}-rolebinding
  namespace: {{ $namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.serviceAccount.name }}
  namespace: {{ $.Values.namespace }}
roleRef:
  kind: Role
  name: {{ $.Values.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}