resources:
  cpu:
    cores: 1
  memory:
    container:
      max: "2Gi"
storage:
  persistentVolume:
    size: "30Gi"
external:
  enabled: true
  type: "NodePort"
  domain: "customredpandadomain.local"
statefulset:
  replicas: 3
  initContainers:
    setDataDirOwnership:
      enabled: true
tls:
  enabled: false
