[book]
authors = ["Damion Werner"]
language = "en"
multilingual = false
src = "src"
title = "JetStream"

[output.html]
additional-js = [
    "./animations/dist/motion-canvas-player/main.js",
    "./animations/dist/animations/project.js",
    ]