[package]
name = "example-eventtime"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
fake = { version = "4.3.0", features = ["chrono", "derive"] }
indexmap = "2.10.0"
malstrom = { path = "../../" }
serde = "1.0.219"
