name: Push Images to GHCR

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push k8s-operator
        uses: docker/build-push-action@v6
        with:
          context: malstrom-k8s
          file: malstrom-k8s/k8s-operator.dockerfile
          push: true
          tags: ghcr.io/malstromdevelopers/k8s-operator:latest,ghcr.io/malstromdevelopers/k8s-operator:${{ github.sha }}
          cache-from: ghcr.io/malstromdevelopers/k8s-operator-cache
          cache-to: ghcr.io/malstromdevelopers/k8s-operator-cache

      - name: Build and Push artifact-manager
        uses: docker/build-push-action@v6
        with:
          context: malstrom-k8s
          file: malstrom-k8s/artifact-manager.dockerfile
          push: true
          tags: ghcr.io/malstromdevelopers/artifact-manager:latest,ghcr.io/malstromdevelopers/artifact-manager:${{ github.sha }}
          cache-from: ghcr.io/malstromdevelopers/artifact-manager
          cache-to: ghcr.io/malstromdevelopers/artifact-manager

      - name: Build and Push artifact-downloader
        uses: docker/build-push-action@v6
        with:
          context: malstrom-k8s
          file: malstrom-k8s/artifact-downloader.dockerfile
          push: true
          tags: ghcr.io/malstromdevelopers/artifact-downloader:latest,ghcr.io/malstromdevelopers/artifact-downloader:${{ github.sha }}
          cache-from: ghcr.io/malstromdevelopers/artifact-downloader
          cache-to: ghcr.io/malstromdevelopers/artifact-downloader
