name: Push Images to GHCR

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push k8s-operator
        uses: docker/build-push-action@v6
        with:
          context: malstrom-k8s
          file: k8s-operator.dockerfile
          push: true
          tags: 
            - malstromdevelopers/k8s-operator/app:latest
            - malstromdevelopers/k8s-operator/app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha

      - name: Build and Push artifact-manager
        uses: docker/build-push-action@v6
        with:
          context: malstrom-k8s
          file: artifact-manager.dockerfile
          push: true
          tags: 
            - malstromdevelopers/artifact-manager/app:latest
            - malstromdevelopers/artifact-manager/app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha

      - name: Build and Push artifact-downloader
        uses: docker/build-push-action@v6
        with:
          context: malstrom-k8s
          file: artifact-downloader.dockerfile
          push: true
          tags: 
            - malstromdevelopers/artifact-downloader/app:latest
            - malstromdevelopers/artifact-downloader/app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
